# How much money will the victi'sm lose when they die? Type Options: "all", "half", "percent", "amount"
# all = Removes all of the victim's Money when they die
# half = Removes half of the victim's Money when they die  
# percent = Removes a percentage of the victim's money. Example, If Money-Loss = 25, 25% of the victim's money will be removed
# amount = Removed the specified amount of money. Example, If Money-Loss = 25, the victim's will lost $25.
Type: percent

# Money-Loss: does not need to be set if Type: is set to "all" or "half"
Money-Loss: 25

# Should the victim lose money if they are not killed by another player
LoseMoneyNaturally: false

# Should the killer gain the money the victim lost?
KillerGainMoney: true
